#!/usr/bin/env bash
# Genesis project entry point.
#
# Show help message or dispatch a given command to a shell script.

set -e

USAGE='Usage: gen [COMMAND] [-h]'

help() {
  echo $USAGE
  echo
  echo 'The COMMAND arg must be one of:'
  echo
  (cd genesis && ls -1 *.sh | sed 's/.sh//')

  echo
  echo 'Options:'
  echo '-h,--help Show this message'

  exit 0
}

if [[ $1 = '-h' ]] || [[ $1 = '--help' ]] || [[ $# -ne 1 ]]; then
  help
fi

SCRIPT="$1.sh"
SCRIPT_PATH="genesis/$SCRIPT"

if [[ ! -f "$SCRIPT_PATH" ]]; then
  echo "ERROR: Could not find script: $SCRIPT_PATH"
  echo
  echo $USAGE
  exit 1
fi

$SCRIPT_PATH
